name: 🏗️ BUILD ANDROID15-6.1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_SOURCE: "https://github.com"
      KERNEL_SOURCE_BRANCH: "mt6878/Galaga/v"
      KERNEL_CONFIG: "galaga_defconfig"

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler rename libelf-dev dwarves

      - name: Download Clang
        run: |
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace/clang
          cd $GITHUB_WORKSPACE/kernel_workspace
          # Качаем напрямую с серверов Google через wget с правильным форматом
          wget -O clang.tar.gz https://googlesource.com
          tar -C clang/ -zxvf clang.tar.gz
          rm clang.tar.gz

      - name: Download Kernel Source
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel

      - name: Setup KernelSU
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          curl -LSs "https://githubusercontent.com" | bash -s main

      - name: Build Kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH
          make -j$(nproc --all) O=out ARCH=arm64 ${{ env.KERNEL_CONFIG }}
          make -j$(nproc --all) CC=clang O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image
